In [2]:
import numpy as np

array_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
array_2 = np.array([1, 2, 3, 4, 5])
array_3 = np.array([6, 7, 8, 9, 10])

result = array_2 + array_3
print(result)

[ 7  9 11 13 15]


In [8]:
array_4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(array_4[array_4 % 2 == 0])
#либо
print(array_4[1::2])

[ 2  4  6  8 10]
[ 2  4  6  8 10]
