In [5]:
import numpy as np

arr_1 = np.random.randint(1, 11, size = (1, 10))
arr_2 = np.random.randint(1, 11, size = (1, 10))
print(arr_1)
print(arr_2)

sum = arr_1 + arr_2
print(sum)

edited_arr = sum.reshape((2, 5))
print(edited_arr)

avg = edited_arr.mean()
print(avg)

[[7 3 8 7 6 5 6 9 4 4]]
[[ 3  2  1  5  1  3  2 10  7  8]]
[[10  5  9 12  7  8  8 19 11 12]]
[[10  5  9 12  7]
 [ 8  8 19 11 12]]
10.1


In [11]:
arr_3 = np.array([[12, 8, 20], [34, 5, 54], [26, 47, 90]])
print(arr_3)

print(arr_3[0][0])

new_arr_3 = arr_3.reshape((9, 1))
print(new_arr_3)

d1_arr_3 = new_arr_3.flatten()
print(d1_arr_3)

[[12  8 20]
 [34  5 54]
 [26 47 90]]
12
[[12]
 [ 8]
 [20]
 [34]
 [ 5]
 [54]
 [26]
 [47]
 [90]]
[12  8 20 34  5 54 26 47 90]


In [13]:
arr_4 = np.random.randint(1, 11, size = (4, 3))
print(arr_4)

arr_4_vstack = np.vstack((arr_4[:, 0], arr_4[:, 1], arr_4[:, 2]))
one_column_arr_4 = arr_4_vstack.reshape((-1, 1))
print(one_column_arr_4)

[[8 2 7]
 [5 8 9]
 [8 8 8]
 [7 2 1]]
[[8]
 [5]
 [8]
 [7]
 [2]
 [8]
 [8]
 [2]
 [7]
 [9]
 [8]
 [1]]


In [16]:
arr_5 = np.random.randint(1, 31, size = (1, 9))
print(arr_5)

print(arr_5.max())

[[14 17 28 28 30 14 15 15 10]]
30


In [18]:
arr_6 = np.random.randint(1, 6, size = (2, 2))
arr_7 = np.random.randint(1, 6, size = (2, 2))
print(arr_6)
print()
print(arr_7)
print()

transposed_arr_6 = np.transpose(arr_6)
print(transposed_arr_6)
print()

transposed_and_arr_7 = transposed_arr_6 + arr_7
print(transposed_and_arr_7)

[[3 1]
 [2 1]]

[[4 4]
 [4 5]]

[[3 2]
 [1 1]]

[[7 6]
 [5 6]]
